substitutions:
  illuminance_update_interval: "2s"
  hidden_ssid: "false"
  log_level: "INFO"

packages:
  package_import_url:
    url: https://github.com/kjake/athom-esp32-configs
    files:
      [
        athom-ld2450-sensor.yaml,
        common/ps02c3mz-base.yaml,
        common/ld2450-base.yaml,
        common/bluetooth-base.yaml,
      ]
    ref: main
    refresh: 1d
