substitutions:
  illuminance_update_interval: "2s"
  hidden_ssid: "false"
  log_level: "INFO"

dashboard_import:
  package_import_url: github://kjake/athom-esp32-configs/athom-ld2450-sensor.yaml@main
  import_full_config: false # or true

packages:
  device_base: !include common/ps02c3mz-base.yaml
  ld2450_base: !include common/ld2450-base.yaml
  bluetooth_base: !include common/bluetooth-base.yaml
