substitutions:
  illuminance_update_interval: "2s"
  hidden_ssid: "false"
  log_level: "NONE"

  device_config:
    ethernet_enabled: false
    co2_enabled: false
    bluetooth_enabled: true
    sensor_variant: "ld2450"
    model: "everything-presence-lite"

dashboard_import:
  package_import_url: github://kjake/athom-esp32-configs/athom-ld2450-sensor.yaml@main
  import_full_config: false

packages:
  device_base: !include common/ps02c3mz-base.yaml
  ld2450_base: !include common/ld2450-base.yaml
  bluetooth_base: !include common/bluetooth-base.yaml
